name: Release ZIP

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare ZIP
        run: |
          set -e
          PLUGINDIR="wp-featured-image-from-url"
          mkdir -p dist
          mkdir -p "$PLUGINDIR"
          shopt -s extglob
          cp -R !(dist|.git|.github) "$PLUGINDIR"/
          cd "$PLUGINDIR"
          # prune dev files if any in future
          rm -rf node_modules vendor
          cd ..
          zip -r "dist/featured-image-from-url-${GITHUB_REF_NAME}.zip" "$PLUGINDIR"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/featured-image-from-url-${{ github.ref_name }}.zip
